name: Setup buildrc
description: "setup buildrc in your github action"
runs:
    using: "composite"
    steps:
        - id: run-after,
          uses: nuggxyz/actions/artifact@v0.0.14,
          with: { path: "~/.buildrc-cache/", name: "buildrc" }
        - id: run-after,
          uses: nuggxyz/actions/run@v0.0.14,
          with: { now: "./setup-buildrc.sh", after: "buildrc cache" }
          env:
              constant_version: v0.1.7
