name: setup buildrc
description: "setup buildrc in your github action"
inputs:
    version:
        description: "the version of buildrc to use"
        required: false
        default: ""
    draft:
        description: "whether to use the draft version of buildrc"
        required: false
        default: ""
    save_cache:
        description: "whether to save the cache"
        required: false
        default: "true"
outputs:
    next_tag:
        value: ${{ steps.buildrc-setup.outputs.BUILDRC_TAG }}
        description: "the version of the build to use"
runs:
    using: "composite"
    steps:
        - name: workflow-cache
          uses: walteh/actions/workflow-cache@v0.0.134
          with:
              path: "/home/runner/.buildrc-ghactions-cache"
              name: "setup-buildrc"
              save: "${{ inputs.save_cache }}"
        - name: buildrc-setup
          uses: walteh/actions/run@v0.0.134
          with:
              before: "${{ github.action_path }}/buildrc-init-env.sh"
              now: "${{ github.action_path }}/buildrc-install.sh ${{ env.auto_version }} ${{ env.file_name_prefix }} ${{ inputs.version }} ${{ inputs.draft }}"
          env:
              auto_version: v0.7.2
              file_name_prefix: buildrc-
