name: Setup buildrc
description: "setup buildrc in your github action"
runs:
    using: "composite"
    steps:
        - name: buildrc-cache
          uses: actions/cache/restore@v3
          id: cache1
          with:
              path: "/home/runner/.buildrc-ghactions-cache"
              key: "${{ runner.os }}-${{ github.workflow }}-buildrc-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}"
        - name: buildrc-cache-save
          uses: actions/cache@v3
          with:
              path: /home/runner/.buildrc-ghactions-cache
              key: "${{ runner.os }}-${{ github.workflow }}-buildrc-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}-${{ github.job }}"
        - name: buildrc-setup
          uses: nuggxyz/actions/run@v0.0.47
          with:
              before: |
                  cache_dir="$HOME/.buildrc-ghactions-cache
                  echo "setting BUILDRC_CACHE_DIR env var to = $cache_dir"
                  echo "BUILDRC_CACHE_DIR=$cache_dir" >> "$GITHUB_ENV"
                  execo="$cache_dir/buildrc-exec-override/buildrc"
                  echo "setting BUILDRC_EXEC_OVERRIDE env var to = $execr"
                  echo "BUILDRC_EXEC_OVERRIDE=$execo" >> "$GITHUB_ENV"
                  temp_dir="$RUNNER_TEMP/.buildrc-ghactions-temp"
                  echo "setting BUILDRC_TEMP_DIR env var to = $temp_dir"
                  echo "BUILDRC_TEMP_DIR=$temp_dir" >> "$GITHUB_ENV"
                  path_dir="$RUNNER_TEMP/.buildrc-ghactions-path"
                  echo "setting BUILDRC_PATH_DIR env var to = $path_dir"
                  echo "BUILDRC_PATH_DIR=$path_dir" >> "$GITHUB_ENV"
                  echo "adding BUILDRC_PATH_DIR to GITHUB_PATH"
                  echo "$path_dir" >> "$GITHUB_PATH"
              now: |
                  # Step 1: Check for buildrc-override
                  echo "Checking for buildrc-override... at $BUILDRC_EXEC_OVERRIDE"
                  if [[ -f "$BUILDRC_EXEC_OVERRIDE" ]]; then
                      echo "Override artifact found. Moving..."
                      mkdir -p temp
                      cp "$BUILDRC_EXEC_OVERRIDE" "$BUILDRC_PATH_DIR/buildrc"
                  else
                      case "$RUNNER_ARCH" in
                      X64) arch="amd64" ;;
                      arm) arch="armv7" ;; # Modify based on your requirements
                      arm64) arch="arm64" ;;
                      *) echo "Unsupported architecture" && exit 1 ;;
                      esac
                      smp_os_arch="${RUNNER_OS,,}-$arch"
                      os_arch_pattern="$smp_os_arch.tar.gz"
                      echo "Override artifact not found. Downloading from GitHub releases... $os_arch_pattern $constant_version"
                      # The name of the release file will be 'os-arch.tar.gz'
                      wrk_dir="$RUNNER_TEMP/setup-buildrc-wrk"
                      gh release download $constant_version -p "$os_arch_pattern" --repo nuggxyz/buildrc --dir "$wrk_dir"
                      tar -xzf "$wrk_dir/$os_arch_pattern" -C "$wrk_dir"
                      cp "$wrk_dir/$smp_os_arch" "$BUILDRC_PATH_DIR/buildrc"
                  fi

                  echo "loading .buildrc"
                  chmod +x "$BUILDRC_PATH_DIR/buildrc"
                  $BUILDRC_PATH_DIR/buildrc load
                  echo "buildrc loaded ✅"
          env:
              constant_version: v0.1.10
