name: Setup buildrc
description: "setup buildrc in your github action"
runs:
    using: "composite"
    steps:
      - name: artifact
        id: artifact
        uses: actions/download-artifact@v3
        with:
          name: buildrc-override
      - name: script
        shell: bash
        run: |
          # Step 1: Check for buildrc-override
          echo "Checking for buildrc-override... at $override_artifact"
          if [[ -f "$override_artifact" ]]; then
            echo "Override artifact found. Moving..."
            mkdir -p temp
            mv "$override_artifact" ./temp/buildrc
          else
            echo "Override artifact not found. Downloading from ghcr..."
            ghcr_url="ghcr.io/nuggxyz/buildrc:${version}"
            docker pull $ghcr_url
            docker save $ghcr_url | tar -xvC temp
          fi

          # Step 2: Setup alias
          echo "Setting up alias..."
          echo "loading .buildrc"
          echo "$GITHUB_WORKSPACE/temp" >> $GITHUB_PATH
          chmod +x ./temp/buildrc
          ./temp/buildrc load .buildrc
          echo "buildrc loaded ✅"
        env:
          version: abc
          override_artifact: ${{ steps.artifact.outputs.download-path }}/linux-amd64
