name: Setup buildrc
description: "setup buildrc in your github action"
runs:
    using: "composite"
    steps:
      - name: artifact
        id: artifact
        uses: actions/download-artifact@v3
      - name: script
        shell: bash
        run: |
          # Step 1: Check for buildrc-override
          echo "Checking for buildrc-override... at $override_artifact"
          if [[ -f "$override_artifact" ]]; then
            echo "Override artifact found. Moving..."
            mkdir -p temp
            mv "$override_artifact" ./temp/buildrc
          else
            case "$RUNNER_ARCH" in
            X64) arch="amd64";;
            arm) arch="armv7";; # Modify based on your requirements
            arm64) arch="arm64";;
            *) echo "Unsupported architecture" && exit 1;;
            esac
            os_arch_pattern="${RUNNER_OS,,}-$arch.tar.gz"
            echo "Override artifact not found. Downloading from GitHub releases... $os_arch_pattern $version"
            # The name of the release file will be 'os-arch.tar.gz'
          
            gh release download $version -p "$os_arch_pattern" --repo nuggxyz/buildrc --dir ./temp/

           
            tar -xzf "./temp/$os_arch_pattern" -C ./temp/
             cd temp/build 
            ls

          fi

          # Step 2: Setup alias
          echo "Setting up alias..."
          echo "loading .buildrc"
          echo "$GITHUB_WORKSPACE/temp" >> $GITHUB_PATH
          chmod +x ./temp/buildrc
          ./temp/buildrc load .buildrc
          echo "buildrc loaded ✅"
        env:
          version: v0.1.2
          override_artifact: ${{ steps.artifact.outputs.download-path }}/buildrc-override/linux-amd64
