name: Setup buildrc
description: "setup buildrc in your github action"
runs:
    using: "composite"
    steps:
        - name: buildrc-cache,
          uses: actions/cache@v3
          with:
              {
                  path: ".buildrc-cache",
                  key: "${{ runner.os }}-${{ github.workflow }}-buildrc-${{ github.run_id }}",
              }
        - name: buildrc-setup,
          uses: nuggxyz/actions/run@v0.0.31
          with: { now: "./setup-buildrc.sh" }
          env:
              constant_version: v0.1.7
