name: setup buildrc
description: "setup buildrc in your github action"
inputs:
    version:
        description: "the version of buildrc to use"
        required: false
        default: ""
    draft:
        description: "whether to use the draft version of buildrc"
        required: false
        default: ""
runs:
    using: "composite"
    steps:
        - name: workflow-cache
          uses: nuggxyz/actions/workflow-cache@v0.0.93
          with:
              path: "/home/runner/.buildrc-ghactions-cache"
              name: "setup-buildrc"
        - name: buildrc-setup
          uses: nuggxyz/actions/run@v0.0.93
          with:
              before: "${{ github.action_path }}/buildrc-init-env.sh"
              now: "${{ github.action_path }}/buildrc-install.sh ${{ env.auto_version }} ${{ env.file_name_prefix }} ${{ inputs.version }} ${{ inputs.draft }}"
          env:
              auto_version: v0.3.1
              file_name_prefix: buildrc-
