#!/usr/bin/env bash

echo "setting up env 🔄"
# artifacts_dir="$HOME/.buildrc-ghactions-artifacts"
# echo "setting BUILDRC_ARTIFACTS_DIR env var to = $artifacts_dir"
# echo "BUILDRC_ARTIFACTS_DIR=$artifacts_dir" >>"$GITHUB_ENV"
# artifacts_to_upload_dir="$HOME/.buildrc-ghactions-artifacts-to-upload"
# echo "setting BUILDRC_ARTIFACTS_DIR env var to = $artifacts_to_upload_dir"
# echo "BUILDRC_ARTIFACTS_TO_UPLOAD_DIR=$artifacts_to_upload_dir" >>"$GITHUB_ENV"
cache_dir="$HOME/.buildrc-ghactions-cache"
echo "setting BUILDRC_CACHE_DIR env var to = $cache_dir"
echo "BUILDRC_CACHE_DIR=$cache_dir" >>"$GITHUB_ENV"
execo="$cache_dir/buildrc-exec-override"
echo "setting BUILDRC_EXEC_OVERRIDE env var to = $execo"
echo "BUILDRC_EXEC_OVERRIDE=$execo" >>"$GITHUB_ENV"
temp_dir="$RUNNER_TEMP/.buildrc-ghactions-temp"
echo "setting BUILDRC_TEMP_DIR env var to = $temp_dir"
echo "BUILDRC_TEMP_DIR=$temp_dir" >>"$GITHUB_ENV"
path_dir="$RUNNER_TEMP/.buildrc-ghactions-path"
echo "setting BUILDRC_PATH_DIR env var to = $path_dir"
echo "BUILDRC_PATH_DIR=$path_dir" >>"$GITHUB_ENV"
echo "adding BUILDRC_PATH_DIR to GITHUB_PATH"
echo "$path_dir" >>"$GITHUB_PATH"
mkdir -p "$path_dir"
mkdir -p "$temp_dir"
mkdir -p "$cache_dir"
# mkdir -p "$artifacts_dir"
# mkdir -p "$artifacts_to_upload_dir"
echo "env set up ✅"
