name: workflow-cache
description: "use this action to cache a directory for the duration of a workflow"
inputs:
    name:
        description: "the unique id for the cache"
        required: false
    path:
        description: "the path to use"
        required: false
    save:
        description: "whether to save the cache"
        required: false
        default: "true"
    load:
        description: "whether to load the cache"
        required: false
        default: "true"
runs:
    using: "composite"
    steps:
        - name: mkdir
          uses: walteh/actions/run@v0.0.134
          with:
              before: |
                  mkdir -p "${{ inputs.path }}"
        - name: restore-previous
          uses: actions/cache/restore@v3
          id: restore
          if: "${{ inputs.load == 'true' }}"
          with:
              path: "${{ inputs.path }}"
              key: "${{ runner.os }}-${{ github.workflow }}-${{ inputs.name }}-${{ github.run_id }}-${{ github.run_number }}-"
        - name: override-previous
          uses: actions/cache@v3
          if: "${{ inputs.save == 'true' }}"
          with:
              path: "${{ inputs.path }}"
              key: "${{ runner.os }}-${{ github.workflow }}-${{ inputs.name }}-${{ github.run_id }}-${{ github.run_number }}-${{ github.job }}"
