name: run

description: "run privileged bash commands"

inputs:
    before:
        description: "shell command"
        required: false
    now:
        description: "shell command"
        required: false
    after:
        description: "shell command"
        required: false

runs:
    using: "node16"
    main: "main.js"
    post: "post.js"
    pre: "pre.js"
