{
    name: bump,
    on:
        {
            schedule: [{ cron: "0 0 * * *" }],
            workflow_dispatch: {},
            push: { branches: [main] },
        },
    permissions: { contents: write, packages: write, workflows: write },
    env: { GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}", BUILDRC: .buildrc },
    jobs:
        {
            main:
                {
                    runs-on: ubuntu-latest,
                    steps:
                        [
                            {
                                name: Check out code,
                                uses: actions/checkout@v3,
                                with: { clean: true, fetch-depth: 0 },
                            },
                            {
                                name: Update formula,
                                id: ref-bump-script,
                                run: "${{ github.workspace }}/scripts/ref_bump.sh",
                            },
                            {
                                name: commit,
                                id: ref-bump-commit,
                                uses: stefanzweifel/git-auto-commit-action@v4,
                                with:
                                    {
                                        file_pattern: "**/*.y*ml",
                                        commit_message: "🤖 (ref-bump) ${{ steps.ref-bump-script.outputs.COMMIT_MESSAGE }}",
                                        commit_author: "github-actions <41898282+github-actions[bot]@users.noreply.github.com>",
                                    },
                            },
                            {
                                name: Bump version and push tag,
                                id: tag,
                                if: "${{ steps.ref-bump-commit.outputs.changes_detected || github.event_name == 'push' }}",
                                uses: anothrNick/github-tag-action@1,
                                env:
                                    {
                                        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}",
                                        WITH_V: true,
                                        DEFAULT_BUMP: patch,
                                        DRY_RUN: true,
                                    },
                            },
                            {
                                name: Update formula,
                                id: self-bump-script,
                                if: "${{ steps.ref-bump-commit.outputs.changes_detected || github.event_name == 'push' }}",
                                run: "${{ github.workspace }}/scripts/self_bump.sh ${{ steps.tag.outputs.new_tag }}",
                            },
                            {
                                name: commit,
                                id: self-bump-commit,
                                uses: stefanzweifel/git-auto-commit-action@v4,
                                with:
                                    {
                                        file_pattern: "**/*.y*ml",
                                        commit_message: "🤖 (self-bump) internal refs to ${{ steps.tag.outputs.new_tag }}",
                                        commit_author: "github-actions <41898282+github-actions[bot]@users.noreply.github.com>",
                                    },
                            },
                            {
                                name: Create GitHub Release,
                                uses: ncipollo/release-action@v1,
                                if: "${{ steps.self-bump-commit.outputs.changes_detected }}",
                                env:
                                    {
                                        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}",
                                    },
                                with:
                                    {
                                        tag: "${{ steps.tag.outputs.new_tag }}",
                                        name: "${{ steps.tag.outputs.new_tag }}",
                                        body: "🤖 auto-generated release for ${{ steps.tag.outputs.new_tag }}",
                                        draft: false,
                                        prerelease: false,
                                    },
                            },
                        ],
                },
        },
}
