{
    on: { workflow_call: null },
    name: buildrc,
    permissions:
        {
            id-token: write,
            contents: write,
            packages: write,
            actions: write,
            deployments: write,
            pull-requests: write,
            issues: write,
            statuses: write,
            checks: write,
        },
    jobs:
        {
            setup:
                {
                    runs-on: ubuntu-latest,
                    env: { GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}" },
                    outputs:
                        {
                            BUILDRC_LOAD_PACKAGE_NAMES_ARRAY: "${{ env.BUILDRC_LOAD_PACKAGE_NAMES_ARRAY }}",
                            BUILDRC_LOAD_USES_GO: "${{ env.BUILDRC_LOAD_USES_GO }}",
                            BUILDRC_LOAD_USES_SWIFT: "${{ env.BUILDRC_LOAD_USES_SWIFT }}",
                            BUILDRC_LOAD_BUILD_ON: "${{ env.BUILDRC_LOAD_BUILD_ON }}",
                        },
                    steps:
                        [
                            {
                                uses: actions/checkout@v3,
                                with: { fetch-depth: 0 },
                            },
                            {
                                id: setup-buildrc,
                                uses: nuggxyz/actions/setup-buildrc@main,
                            },
                            { id: setup-release, run: "buildrc release setup" },
                        ],
                },
            build:
                {
                    runs-on: "${{ fromJson(needs.setup.outputs.BUILDRC_LOAD_BUILD_ON) }}-latest",
                    env: { GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}" },
                    needs: [setup],
                    steps:
                        [
                            {
                                uses: actions/checkout@v3,
                                with: { fetch-depth: 0 },
                            },
                            {
                                id: setup-buildrc,
                                uses: nuggxyz/actions/setup-buildrc@main,
                            },
                            {
                                id: setup-go,
                                if: "${{ fromJson(needs.setup.outputs.BUILDRC_LOAD_USES_GO) }}",
                                uses: actions/setup-go@v2,
                            },
                            { id: build, run: "buildrc release build" },
                        ],
                },
            docker:
                {
                    runs-on: ubuntu-latest,
                    env: { GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}" },
                    needs: [setup, build],
                    strategy:
                        {
                            matrix:
                                {
                                    package: "${{ fromJson(needs.setup.outputs.BUILDRC_LOAD_PACKAGE_NAMES_ARRAY) }}",
                                },
                        },
                    steps:
                        [
                            {
                                uses: actions/checkout@v3,
                                with: { fetch-depth: 0 },
                            },
                            {
                                id: setup-buildrc,
                                uses: nuggxyz/actions/setup-buildrc@main,
                            },
                            {
                                id: container,
                                run: "buildrc release container '${{ matrix.package }}'",
                            },
                            {
                                id: helper,
                                uses: nuggxyz/actions/buildrc-docker-helper@main,
                            },
                        ],
                },

            finalize:
                {
                    runs-on: ubuntu-latest,
                    env: { GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}" },
                    needs: [docker],
                    steps:
                        [
                            {
                                uses: actions/checkout@v3,
                                with: { fetch-depth: 0 },
                            },
                            {
                                id: setup-buildrc,
                                uses: nuggxyz/actions/setup-buildrc@main,
                            },
                            { id: finalize, run: "buildrc release finalize" },
                            { id: upload, run: "buildrc release upload" },
                        ],
                },
        },
}
